#!/usr/bin/env bun
/**
 * Embed the skills and agents under src/assets into a generated TypeScript
 * module, so the compiled single-file binary carries them and can extract
 * them on first run.
 *
 * Run automatically from script/build.ts; safe to run by hand while iterating.
 */

import { createHash } from "crypto"
import fs from "fs"
import path from "path"

const ROOT = path.join(import.meta.dir, "..")
const ASSET_DIR = path.join(ROOT, "src", "assets")
const OUT = path.join(ROOT, "src", "config", "bundled-assets.gen.ts")

/** Extensions treated as text; everything else is base64-encoded. */
const TEXT_EXT = new Set([
  ".md", ".txt", ".json", ".jsonc", ".yaml", ".yml", ".js", ".cjs", ".mjs",
  ".ts", ".sh", ".html", ".css", ".xml", ".toml", ".py",
])

function walk(dir: string, base = dir): string[] {
  if (!fs.existsSync(dir)) return []
  const out: string[] = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walk(full, base))
    else if (entry.isFile()) out.push(path.relative(base, full))
  }
  return out.sort()
}

const files = walk(ASSET_DIR)
if (files.length === 0) {
  console.warn("gen-bundled-assets: no assets found under src/assets")
}

const hash = createHash("sha256")
const entries: string[] = []

for (const rel of files) {
  const abs = path.join(ASSET_DIR, rel)
  const buf = fs.readFileSync(abs)
  const isText = TEXT_EXT.has(path.extname(rel).toLowerCase())
  const content = isText ? buf.toString("utf8") : buf.toString("base64")
  // Assets land in the config dir at the same relative path.
  const outPath = rel.split(path.sep).join("/")
  hash.update(outPath).update(buf)
  entries.push(
    `  { path: ${JSON.stringify(outPath)}, content: ${JSON.stringify(content)}, base64: ${!isText} },`,
  )
}

const version = hash.digest("hex").slice(0, 16)
const banner = `// GENERATED by script/gen-bundled-assets.ts — do not edit by hand.
// ${files.length} files embedded. Regenerated on every build.
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(
  OUT,
  `${banner}
export const BUNDLED_ASSETS_VERSION = ${JSON.stringify(version)}

export const BUNDLED_ASSETS: { path: string; content: string; base64: boolean }[] = [
${entries.join("\n")}
]
`,
)

console.log(`gen-bundled-assets: embedded ${files.length} files (version ${version})`)
